/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./../src/components/layout/AppHeader.vue')['default']
    CfgViewer: typeof import('./../src/components/analysis/CfgViewer.vue')['default']
    CodeViewer: typeof import('./../src/components/editor/CodeViewer.vue')['default']
    ConstantsPanel: typeof import('./../src/components/analysis/ConstantsPanel.vue')['default']
    DiffViewer: typeof import('./../src/components/editor/DiffViewer.vue')['default']
    FileListItem: typeof import('./../src/components/layout/FileListItem.vue')['default']
    FilePanel: typeof import('./../src/components/layout/FilePanel.vue')['default']
    FileTreeFolder: typeof import('./../src/components/layout/FileTreeFolder.vue')['default']
    FileTreeView: typeof import('./../src/components/layout/FileTreeView.vue')['default']
    IMdiChevronDown: typeof import('~icons/mdi/chevron-down')['default']
    IMdiChevronUp: typeof import('~icons/mdi/chevron-up')['default']
    IMdiClose: typeof import('~icons/mdi/close')['default']
    IMdiCodeBraces: typeof import('~icons/mdi/code-braces')['default']
    IMdiDotsVertical: typeof import('~icons/mdi/dots-vertical')['default']
    IMdiFileDocumentMultipleOutline: typeof import('~icons/mdi/file-document-multiple-outline')['default']
    IMdiFileTreeOutline: typeof import('~icons/mdi/file-tree-outline')['default']
    IMdiFolderOutline: typeof import('~icons/mdi/folder-outline')['default']
    IMdiFolderPlusOutline: typeof import('~icons/mdi/folder-plus-outline')['default']
    IMdiGithub: typeof import('~icons/mdi/github')['default']
    IMdiHarddisk: typeof import('~icons/mdi/harddisk')['default']
    IMdiMagnify: typeof import('~icons/mdi/magnify')['default']
    IMdiPlus: typeof import('~icons/mdi/plus')['default']
    IMdiShieldCheckOutline: typeof import('~icons/mdi/shield-check-outline')['default']
    IMdiTranslate: typeof import('~icons/mdi/translate')['default']
    IMdiTrayArrowDown: typeof import('~icons/mdi/tray-arrow-down')['default']
    IMdiTrayArrowUp: typeof import('~icons/mdi/tray-arrow-up')['default']
    IMdiTuneVariant: typeof import('~icons/mdi/tune-variant')['default']
    IMdiWeatherNight: typeof import('~icons/mdi/weather-night')['default']
    IMdiWhiteBalanceSunny: typeof import('~icons/mdi/white-balance-sunny')['default']
    IMdiWrap: typeof import('~icons/mdi/wrap')['default']
    MainContent: typeof import('./../src/components/layout/MainContent.vue')['default']
    NA: typeof import('naive-ui')['NA']
    NAlert: typeof import('naive-ui')['NAlert']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NProgress: typeof import('naive-ui')['NProgress']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    NTooltip: typeof import('naive-ui')['NTooltip']
    ProtoGraph: typeof import('./../src/components/analysis/ProtoGraph.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsDrawer: typeof import('./../src/components/settings/SettingsDrawer.vue')['default']
    WelcomeView: typeof import('./../src/components/layout/WelcomeView.vue')['default']
  }
}
