-- 多个 call-result local 在后续仍有读取；观察分析按绑定读写事件推进。
-- unluac: expect-not-contains [[unluac error]]
-- unluac: expect-ast-min [[local-decl]] [[64]]
local function make() return {} end
local function run()
local v0 = make()
local v1 = make()
local v2 = make()
local v3 = make()
local v4 = make()
local v5 = make()
local v6 = make()
local v7 = make()
local v8 = make()
local v9 = make()
local v10 = make()
local v11 = make()
local v12 = make()
local v13 = make()
local v14 = make()
local v15 = make()
local v16 = make()
local v17 = make()
local v18 = make()
local v19 = make()
local v20 = make()
local v21 = make()
local v22 = make()
local v23 = make()
local v24 = make()
local v25 = make()
local v26 = make()
local v27 = make()
local v28 = make()
local v29 = make()
local v30 = make()
local v31 = make()
local v32 = make()
local v33 = make()
local v34 = make()
local v35 = make()
local v36 = make()
local v37 = make()
local v38 = make()
local v39 = make()
local v40 = make()
local v41 = make()
local v42 = make()
local v43 = make()
local v44 = make()
local v45 = make()
local v46 = make()
local v47 = make()
local v48 = make()
local v49 = make()
local v50 = make()
local v51 = make()
local v52 = make()
local v53 = make()
local v54 = make()
local v55 = make()
local v56 = make()
local v57 = make()
local v58 = make()
local v59 = make()
local v60 = make()
local v61 = make()
local v62 = make()
local v63 = make()
return v0 ~= nil and v1 ~= nil and v2 ~= nil and v3 ~= nil and v4 ~= nil and v5 ~= nil and v6 ~= nil and v7 ~= nil and v8 ~= nil and v9 ~= nil and v10 ~= nil and v11 ~= nil and v12 ~= nil and v13 ~= nil and v14 ~= nil and v15 ~= nil and v16 ~= nil and v17 ~= nil and v18 ~= nil and v19 ~= nil and v20 ~= nil and v21 ~= nil and v22 ~= nil and v23 ~= nil and v24 ~= nil and v25 ~= nil and v26 ~= nil and v27 ~= nil and v28 ~= nil and v29 ~= nil and v30 ~= nil and v31 ~= nil and v32 ~= nil and v33 ~= nil and v34 ~= nil and v35 ~= nil and v36 ~= nil and v37 ~= nil and v38 ~= nil and v39 ~= nil and v40 ~= nil and v41 ~= nil and v42 ~= nil and v43 ~= nil and v44 ~= nil and v45 ~= nil and v46 ~= nil and v47 ~= nil and v48 ~= nil and v49 ~= nil and v50 ~= nil and v51 ~= nil and v52 ~= nil and v53 ~= nil and v54 ~= nil and v55 ~= nil and v56 ~= nil and v57 ~= nil and v58 ~= nil and v59 ~= nil and v60 ~= nil and v61 ~= nil and v62 ~= nil and v63 ~= nil
end
assert(run())

local function seed() return { tag = 1 } end
local function replace(old) return { tag = old.tag + 1 } end
local function overwrite(flag)
    local object = seed()
    if flag then object = replace(object) end
    object = replace(object)
    return object.tag
end
assert(overwrite(false) == 2)
assert(overwrite(true) == 3)
print("regress495", run(), overwrite(false), overwrite(true))
