-- 连续条件的入口 phi 是本区域输入；逐次状态和调用顺序必须保留。
-- unluac: expect-not-contains [[unluac error]]
-- unluac: expect-ast-count [[if]] [[512]]
local function run(f, x)
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    if x % 2 == 0 then x = f(x) else x = x + 1 end
    return x
end
for start = 0, 1 do
    local calls = 0
    local result = run(function(x)
        assert(x == calls * 2 + start * 2)
        calls = calls + 1
        return x + 1
    end, start)
    assert(result == 512 + start and calls == 256)
    print(start, result, calls)
end
