//! 回归 case 101–200；保持按历史编号的稳定执行顺序，不负责 case 展开。

use super::*;

pub(super) const REGRESSION_CASES_101_200: &[LuaCaseMatrixEntry] = &[
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_101_branch_into_loop_header_phi.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_102_implicit_else_loop_backedge.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_103_repeat_nested_loop_shared_tail.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_104_luau_repeat_skip_numeric_for.lua",
        LUAU_ONLY,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_105_luau_same_header_loop_path_owner.lua",
        LUAU_ONLY,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_106_luau_repeat_current_iteration_tail.lua",
        LUAU_ONLY,
    )
    .with_options(LUAU_OPTIMIZED_OPTIONS),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_107_luau_linear_break_exit_pad.lua",
        LUAU_ONLY,
    )
    .with_options(LUAU_OPTIMIZED_OPTIONS),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_108_luau_repeat_optimized_core_tail.lua",
        LUAU_ONLY,
    )
    .with_options(LUAU_OPTIMIZED_OPTIONS),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_109_luau_repeat_condition_entry_state.lua",
        LUAU_ONLY,
    )
    .with_options(LUAU_OPTIMIZED_OPTIONS),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_110_luau_generic_for_exit_break_pad.lua",
        LUAU_ONLY,
    )
    .with_options(LUAU_OPTIMIZED_OPTIONS),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_110_luau_generic_for_exit_break_pad.lua",
        LUA_51_AND_LUAJIT,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_111_luau_short_continue_shared_tail.lua",
        LUAU_ONLY,
    )
    .with_options(LUAU_OPTIMIZED_OPTIONS),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_112_luau_continue_merge_state_owner.lua",
        LUAU_ONLY,
    )
    .with_variants(LUAU_ALL_OPTIMIZATION_VARIANTS),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_113_luau_short_circuit_outer_break.lua",
        LUAU_ONLY,
    )
    .with_options(LUAU_OPTIMIZED_OPTIONS),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_114_luau_repeat_shared_nested_loop_tail.lua",
        LUAU_ONLY,
    )
    .with_options(LUAU_OPTIMIZED_OPTIONS),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_115_luau_branch_mixed_entry_update_owner.lua",
        LUAU_ONLY,
    )
    .with_options(LUAU_OPTIMIZED_OPTIONS),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_116_luau_numeric_for_shared_nested_preheader.lua",
        LUAU_ONLY,
    )
    .with_options(LUAU_OPTIMIZED_OPTIONS),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_117_luau_repeat_continue_pad_shared_tail.lua",
        LUAU_ONLY,
    )
    .with_options(LUAU_OPTIMIZED_OPTIONS),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_118_luau_early_continue_nested_loop_tail.lua",
        LUAU_ONLY,
    )
    .with_options(LUAU_OPTIMIZED_OPTIONS),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_119_luau_repeat_continue_pad_owner.lua",
        LUAU_ONLY,
    )
    .with_options(LUAU_OPTIMIZED_OPTIONS),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_120_luau_short_continue_nested_tail_break.lua",
        LUAU_ONLY,
    )
    .with_options(LUAU_OPTIMIZED_OPTIONS),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_121_luau_short_circuit_immediate_repeat_break.lua",
        LUAU_ONLY,
    )
    .with_options(LUAU_OPTIMIZED_OPTIONS),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_122_luau_same_header_loop_break_owner.lua",
        LUAU_ONLY,
    )
    .with_options(LUAU_OPTIMIZED_OPTIONS),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_123_luau_dual_early_return_soft_merge.lua",
        LUAU_ONLY,
    )
    .with_options(LUAU_OPTIMIZED_OPTIONS),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_124_luau_loop_break_header_phi_owner.lua",
        LUAU_ONLY,
    )
    .with_options(LUAU_OPTIMIZED_OPTIONS),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_125_luau_repeat_condition_side_effect.lua",
        LUAU_ONLY,
    )
    .with_options(LUAU_OPTIMIZED_OPTIONS),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_126_lua51_legacy_arg_table.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_127_puc54_metamethod_operand_flip.lua",
        PUC_LUA_GE_54,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_128_same_header_plain_nested_loops.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_129_lua51_nonempty_backedge_pad.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_130_env_keyword_table_access.lua",
        PUC_LUA_GE_52,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_131_lua55_anonymous_vararg.lua",
        PUC_LUA_GE_55,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_132_luajit_infinite_imaginary.lua",
        LUAJIT_ONLY,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_133_luajit_wide_compare_operand.lua",
        LUAJIT_ONLY,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_134_negative_literal_power.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_135_same_header_sibling_latches.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_136_luau_global_operands.lua",
        LUAU_ONLY,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_137_luajit_contextual_goto.lua",
        LUAJIT_ONLY,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_138_luau_contextual_continue.lua",
        LUAU_ONLY,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_139_lua55_contextual_global.lua",
        PUC_LUA_GE_55,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_140_luajit_prior_handoff_target.lua",
        LUAJIT_ONLY,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_141_lua51_vararg_fixed_results.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_142_loop_multi_exit_downstream_value_merge.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_143_loop_parameter_entry_value.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_144_loop_header_eval_order.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_145_loop_header_snapshot.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_146_direct_method_receiver_eval_count.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_147_inline_call_alias_eval_order.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_148_luau_repeat_recompile_state_owner.lua",
        LUAU_ONLY,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_149_lua51_single_arm_nested_generic_for.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_150_luau_numeric_for_branch_owner.lua",
        LUAU_ONLY,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_151_luau_nested_repeat_short_circuit_merge.lua",
        LUAU_ONLY,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_152_luau_while_continue_break_tail.lua",
        LUAU_ONLY,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_153_lua55_generic_for_close_break_pad.lua",
        PUC_LUA_GE_55,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_154_lua55_generic_for_binding_scope.lua",
        PUC_LUA_GE_55,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_155_outer_for_binding_inner_loops.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_156_numeric_for_binding_inner_loop.lua",
        MUTABLE_NUMERIC_FOR_BINDING_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_157_repeat_nested_break_return.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_158_luau_short_circuit_break_shared_tail.lua",
        LUAU_ONLY,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_159_cross_slot_snapshot_loop_state.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_160_captured_slot_receiver_eval.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_161_lua55_abs_line_info_layout.lua",
        PUC_LUA_GE_55,
    )
    .with_options(LuaCaseOptions {
        retain_debug: true,
        ..LuaCaseOptions::DEFAULT
    }),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_162_table_checkpoint_new_pending_rollback.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_163_lua54_wide_env_upvalue.lua",
        PUC_LUA_GE_54,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_164_lua55_wide_global_decl.lua",
        PUC_LUA_GE_55,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_165_global_name_binding_shadow.lua",
        PUC_LUA_GE_52,
    )
    .with_options(LuaCaseOptions {
        retain_debug: true,
        naming_mode: Some(NamingMode::Simple),
        ..LuaCaseOptions::DEFAULT
    }),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_166_parenthesized_call_separator.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_167_same_header_repeat_short_circuit.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_168_puc_repeat_condition_exit.lua",
        PUC_LUA_ALL,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_169_same_header_conditional_sibling_latch.lua",
        PUC_LUA_ALL,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_170_same_header_repeat_body.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_171_captured_alias_group_home_slot.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_172_temp_inline_eval_regions.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_173_terminal_return_call_order.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_174_explicit_value_pack.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_175_lua54_close_value_pack.lua",
        PUC_LUA_GE_54,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_176_sibling_latch_terminal_loop.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_177_lua55_generic_for_live_out.lua",
        PUC_LUA_GE_55,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_178_observable_expression_reads.lua",
        ALL_NON_LUAU_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_179_long_bracket_suffix_delimiter.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_180_numeric_for_shared_tail.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_181_generic_for_branch_phi.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_182_numeric_for_before_irreducible_goto.lua",
        LUA_GOTO_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_183_mixed_irreducible_explicit_close.lua",
        PUC_LUA_GE_54,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_184_mixed_irreducible_generic_close.lua",
        PUC_LUA_GE_54,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_185_branch_control_forward_guards.lua",
        LUA_GOTO_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_186_truthy_ternary_hir_owner.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_187_irreducible_plain_loop_owner.lua",
        LUA_GOTO_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_188_luau_nan_fixed_point.lua",
        LUAU_ONLY,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_189_terminal_empty_return_guard.lua",
        LUAU_ONLY,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_190_luau_import_open_pack.lua",
        LUAU_ONLY,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_191_vararg_open_pack_setup.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_192_luau_open_pack_callee_move.lua",
        LUAU_ONLY,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_193_luau_unreachable_numeric_for_control.lua",
        LUAU_ONLY,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_194_discarded_table_open_tail.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_195_terminal_exit_unknown_loop.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_196_child_writes_parent_capture.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_197_long_bracket_control_byte.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_198_local_scope_limit.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_199_nested_local_scope_budget.lua",
        LUAU_ONLY,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_200_close_managed_writable_capture.lua",
        ALL_DIALECTS,
    ),
];
