//! 回归 case 001–100；保持按历史编号的稳定执行顺序，不负责 case 展开。

use super::*;

pub(super) const REGRESSION_CASES_001_100: &[LuaCaseMatrixEntry] = &[
    // ── regression / adversarial cases ──
    // 这些 case 暴露了已知反编译 bug，单独建文件避免 decompile/runtime 失败波及同文件其他 proto。
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_01_boolean_adversarial.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_02_repeat_inner_ref.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_03_guarded_return_chain.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_04_short_circuit_header_call.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_05_if_else_short_circuit_shared_body.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_06_nested_repeat_continue_flag.lua",
        ALL_DIALECTS,
    )
    .with_options(LuaCaseOptions {
        retain_debug: true,
        ..LuaCaseOptions::DEFAULT
    }),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_07_close_scope_slot_reuse.lua",
        PUC_LUA_GE_53,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_08_goto_loop_phi_seed.lua",
        PUC_LUA_GE_53,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_09_loadnil_capture_range.lua",
        PUC_LUA_GE_52,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_10_loop_closure_capture_slot.lua",
        PUC_LUA_GE_52,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_11_assert_short_circuit_value_merge.lua",
        PUC_LUA_GE_52,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_11_assert_short_circuit_value_merge.lua",
        LUAU_ONLY,
    )
    .with_variants(LUAU_ALL_OPTIMIZATION_VARIANTS),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_12_loop_break_shared_continuation.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_13_entry_loop_state.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_07_method_receiver_single_value.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_08_global_table_install_readability.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_09_mechanical_call_and_for_inline.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_10_lua51_event_guard_goto_recovery.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_11_branch_carried_closure_capture.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_12_nested_bvm_short_circuit_tail.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_13_if_then_merge_ownership.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_14_generic_for_nested_continue.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_15_generic_for_terminal_guard.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_16_numeric_for_terminal_body.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_17_generic_for_break_pad.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_18_short_circuit_loop_shared_tail.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_19_generic_for_break_tail_binding.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_20_numeric_for_latch_shared_else.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_21_shared_terminal_return.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_22_short_circuit_pure_call_operand.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_23_or_guard_shared_tail.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_24_branch_shared_continuation.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_25_table_setlist_trailing_short_circuit.lua",
        LUA_51_AND_LUAU,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_26_forward_capture_function_coalesce.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_27_while_true_latch_tail.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_28_lua51_loop_branch_recovery.lua",
        PUC_LUA_51,
    )
    .with_options(LuaCaseOptions {
        retain_debug: true,
        ..LuaCaseOptions::DEFAULT
    })
    .with_variants(ALL_NAMING_VARIANTS),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_29_lua51_retry_loop_live_out.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_30_table_setlist_nested_producer.lua",
        PUC_LUA_51,
    )
    .with_expectation(LuaCaseExpectation::TableSetListResidual),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_31_numeric_for_terminal_branch_coverage.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_32_generic_for_immediate_break.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_33_table_setlist_binary_producer.lua",
        PUC_LUA_51,
    )
    .with_expectation(LuaCaseExpectation::TableSetListResidual),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_34_short_circuit_exit_jump_pad.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_35_multi_entry_loop_state.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_36_nil_fallback_alias.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_37_shared_terminal_closure_tail.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_38_method_chain_live_receiver.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_39_method_hint_open_arg_call.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_40_branch_state_and_short_prefix_escape.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_41_negated_relational_metamethod.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_42_call_arg_eval_order.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_43_global_arg_eval_order.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_44_loop_cond_eval_order.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_45_inline_stmt_eval_order.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_47_conditional_reassign_multi_phi.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_48_decision_value_truthiness.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_49_closure_capture_branch_write.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_50_method_chain_dead_local_side_effect.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_51_method_hint_short_circuit_arg.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_52_table_trailing_multivalue_boundary.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_53_loop_exit_state_preheader.lua",
        ALL_NON_LUAU_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_54_method_alias_wide_call_args.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_55_leading_newline_string.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_56_negative_zero_float.lua",
        PUC_LUA_GE_53,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_57_utf8_control_string.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_58_binary_string_bytes.lua",
        ALL_NON_LUAU_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_59_integer_min_literal.lua",
        PUC_LUA_GE_53,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_60_integral_float_literal.lua",
        PUC_LUA_GE_53,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_61_numeric_for_float_step.lua",
        PUC_LUA_GE_53,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_62_keyword_method_name.lua",
        PUC_LUA_GE_55,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_63_shared_fallback_value_merge.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_64_multiret_global_and_return_alias.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_65_method_decl_captured_owner.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_66_preserved_value_guard.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_67_branch_update_used_after_if.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_68_multi_value_merge_defer_to_bvm.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_69_infinite_loop_branch_merge.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_70_infinite_loop_local_merge.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_71_shared_tail_loop_path_check.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_72_loop_exit_generic_owner.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_73_branch_owns_nested_loop_exit_phi.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_74_degenerate_numeric_for.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_75_guard_bvm_priority.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_76_luau_empty_generic_for.lua",
        LUAU_ONLY,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_77_loop_nested_break_continuation.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_78_adjacent_loop_state_handoff.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_79_generic_for_short_break.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_80_same_header_nested_loops.lua",
        LUAU_ONLY,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_81_degenerate_numeric_for_exit_pad.lua",
        LUAU_ONLY,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_82_numeric_for_control_pad.lua",
        LUAU_ONLY,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_83_nested_break_exit_pad.lua",
        LUAU_ONLY,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_84_nested_loop_scope_state.lua",
        LUAU_ONLY,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_85_repeat_nested_numeric_body.lua",
        LUAU_ONLY,
    )
    .with_variants(LUAU_ALL_OPTIMIZATION_VARIANTS),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_86_numeric_for_duplicated_return_state.lua",
        LUAU_ONLY,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_87_repeat_short_condition_in_degenerate_generic_for.lua",
        LUAU_ONLY,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_88_repeat_degenerate_continue_branch.lua",
        LUAU_ONLY,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_89_loop_break_terminal_split.lua",
        LUAU_ONLY,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_90_degenerate_numeric_for_nested_while.lua",
        LUAU_ONLY,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_91_branch_owned_multi_entry_loop_state.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_92_repeat_single_condition_and_generic_break.lua",
        LUAU_ONLY,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_93_numeric_for_continue_pad_state.lua",
        LUAU_ONLY,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_94_multi_exit_loop_terminal_state.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_95_luau_shared_continue_edge_owner.lua",
        LUAU_ONLY,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_96_luau_loop_exit_bounded_branch.lua",
        LUAU_ONLY,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_97_repeat_header_break_pad.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_98_short_circuit_shared_return_value.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_99_nested_loop_branch_state_seed.lua",
        LUAU_ONLY,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_100_adjacent_loop_redefining_header_state.lua",
        ALL_DIALECTS,
    ),
];
