//! 回归 case 201–318；保持按历史编号的稳定执行顺序，不负责 case 展开。

use super::*;

pub(super) const REGRESSION_CASES_201_318: &[LuaCaseMatrixEntry] = &[
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_201_repeat_live_out.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_202_irreducible_numeric_for_owner.lua",
        LUA_GOTO_DIALECTS,
    )
    .with_structure_contracts(&[LuaCaseStructureContract::MixedUnstructuredChildLoop {
        dialect: LuaCaseDialect::Lua54,
        protocol: LuaCaseLoopProtocol::NumericFor,
    }]),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_203_irreducible_generic_for_owner.lua",
        LUA_GOTO_DIALECTS,
    )
    .with_structure_contracts(&[LuaCaseStructureContract::MixedUnstructuredChildLoop {
        dialect: LuaCaseDialect::Lua54,
        protocol: LuaCaseLoopProtocol::GenericFor,
    }]),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_204_irreducible_explicit_close_owner.lua",
        PUC_LUA_GE_54,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_205_while_true_header_guard.lua",
        PUC_LUA_ALL,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_206_luau_home_slot_compaction.lua",
        LUAU_ONLY,
    )
    .with_variants(LUAU_ALL_OPTIMIZATION_VARIANTS),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_207_decision_naturalize_budget.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_208_short_circuit_repeat_state_init.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_209_method_fixed_prefix_open_tail.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_210_repeat_multileaf_backedges.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_211_temp_inline_binding_snapshot.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_212_table_constructor_field_order.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_213_numeric_for_short_circuit_assignment.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_214_loop_if_then_continuation.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_215_repeat_short_circuit_state.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_216_irreducible_linear_exit.lua",
        PUC_LUA_GE_52,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_217_terminal_close_capture_epoch.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_218_parent_write_terminal_capture.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_219_luau_capture_value_reuse.lua",
        LUAU_ONLY,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_220_branch_close_capture_epoch.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_221_repeat_candidate_identity.lua",
        ALL_NON_LUAU_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_222_shared_short_circuit_dag.lua",
        ALL_NON_LUAU_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_223_multiret_global_write_order.lua",
        ALL_NON_LUAU_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_224_table_capture_writeback.lua",
        ALL_NON_LUAU_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_225_repeat_shared_condition_break.lua",
        ALL_NON_LUAU_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_225_repeat_shared_condition_break.lua",
        LUAU_ONLY,
    )
    .with_variants(LUAU_ALL_OPTIMIZATION_VARIANTS),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_226_repeat_direct_break_condition_owner.lua",
        ALL_NON_LUAU_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_227_while_short_condition_body_backedge.lua",
        ALL_NON_LUAU_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_227_while_short_condition_body_backedge.lua",
        LUAU_ONLY,
    )
    .with_variants(LUAU_ALL_OPTIMIZATION_VARIANTS),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_228_generic_for_cleanup_shared_continuation.lua",
        ALL_NON_LUAU_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_229_long_short_circuit_chain.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_230_numeric_for_tbc_break.lua",
        PUC_LUA_GE_54,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_231_repeat_refine_exit_phi_owner.lua",
        ALL_NON_LUAU_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_232_parent_write_after_reference_capture.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_233_raw_branch_value_before_locals.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_234_nested_phi_short_value_merge.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_235_table_constructor_eval_ownership.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_236_table_constructor_pending_alias.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_237_table_constructor_open_overlap.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_238_nested_loop_owner_exit.lua",
        PUC_LUA_GE_52,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_239_lua55_degenerate_generic_scope.lua",
        PUC_LUA_GE_55,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_240_lua55_tforprep_swap.lua",
        PUC_LUA_GE_55,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_241_branch_value_single_eval.lua",
        PUC_LUA_ALL,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_242_repeat_nested_break_shared_fallthrough.lua",
        ALL_NON_LUAU_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_243_repeat_tbc_iteration_scope.lua",
        PUC_LUA_GE_54,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_244_effectful_errnnil_tbc.lua",
        PUC_LUA_GE_55,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_245_observable_repeat_prefix_ops.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_246_repeat_nested_close_scope.lua",
        PUC_LUA_GE_54,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_247_disconnected_if_else_no_merge.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_248_luajit_negated_compare.lua",
        LUAJIT_ONLY,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_249_boolean_shell_table_lvalue_order.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_250_ast_inline_ordered_snapshot.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_251_method_alias_sink_order.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_252_materialize_preserves_eval.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_253_luau_deferred_open_setlist.lua",
        LUAU_ONLY,
    )
    .with_options(LUAU_OPTIMIZED_OPTIONS),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_254_table_constructor_handoff_snapshot.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_255_header_retry_terminal_state.lua",
        LUA_51_AND_LUAJIT,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_256_nested_loop_header_arm.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_257_enclosing_loop_escape_fence.lua",
        PUC_LUA_ALL,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_258_short_circuit_subject_ownership.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_259_env_snapshot_identity.lua",
        PUC_LUA_GE_52,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_260_lua55_degenerate_generic_shared_exit.lua",
        PUC_LUA_GE_55,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_261_branch_shared_continuation_nearest.lua",
        PUC_LUA_GE_52,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_262_infinite_loop_nearest_merge.lua",
        PUC_LUA_GE_52,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_263_repeat_tail_temp_inline.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_264_phi_home_slot_local_limit.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_265_entry_loop_exit_state.lua",
        LUA_51_AND_LUAJIT,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_266_branch_exit_prefix_effect.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_267_branch_value_mutable_source_snapshot.lua",
        MUTABLE_NUMERIC_FOR_BINDING_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_268_short_circuit_nonempty_continue_reentry.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_270_luau_repeat_condition.lua",
        LUAU_ONLY,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_271_loop_break_soft_phi.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_272_lua52_goto_capture_identity.lua",
        LUA_GOTO_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_273_close_capture_post_slot_reuse.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_274_temp_live_use_boundaries.lua",
        ALL_NON_LUAU_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_274_temp_live_use_boundaries.lua",
        LUAU_ONLY,
    )
    .with_options(LUAU_OPTIMIZED_OPTIONS),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_275_nested_loop_body_scope_exit.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_276_degenerate_generic_body_region.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_277_boundary_alias_snapshot.lua",
        LUA_GOTO_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_278_conditional_captured_writeback.lua",
        PUC_LUA_GE_52,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_279_repeat_short_body_scope_break.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_280_nested_loop_break_shared_tail.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_281_while_nested_loop_outer_break.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_282_long_logical_ast_depth.lua",
        PUC_LUA_54,
    )
    .with_options(NO_RECOMPILE_STRESS_OPTIONS),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_283_nested_table_candidate.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_284_luau_short_bvm_terminal_loop.lua",
        LUAU_ONLY,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_285_short_circuit_nested_break_tail.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_286_luau_continue_bvm_shared_tail.lua",
        LUAU_ONLY,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_287_luau_continue_nested_loop_tail.lua",
        LUAU_ONLY,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_288_luau_shared_proto_dag.lua",
        LUAU_ONLY,
    )
    .with_options(LUAU_OPTIMIZED_OPTIONS),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_289_luau_closure_creation_identity.lua",
        LUAU_ONLY,
    )
    .with_options(LUAU_OPTIMIZED_OPTIONS),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_290_luau_numeric_for_early_continue_tail.lua",
        LUAU_ONLY,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_291_luau_inlined_loop_stateful_exit.lua",
        LUAU_ONLY,
    )
    .with_options(LUAU_OPTIMIZED_OPTIONS),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_292_lua51_short_while_break_shared_tail.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_293_puc_nested_repeat_break_live_out.lua",
        PUC_LUA_ALL,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_294_luau_continue_shared_break_tail.lua",
        LUAU_ONLY,
    )
    .with_variants(LUAU_ALL_OPTIMIZATION_VARIANTS),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_295_lua51_unsupported_island_contract.lua",
        PUC_LUA_51,
    )
    .with_expectation(LuaCaseExpectation::UnsupportedIsland {
        jump_pc: 7,
        target_pc: 13,
    }),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_296_luau_captured_shared_factory.lua",
        LUAU_ONLY,
    )
    .with_options(LUAU_OPTIMIZED_CONVERGENCE_OPTIONS),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_297_luau_decision_guard_mutation.lua",
        LUAU_ONLY,
    )
    .with_variants(LUAU_ALL_OPTIMIZATION_VARIANTS),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_298_luau_captured_shared_capture_free_dependency.lua",
        LUAU_ONLY,
    )
    .with_options(LUAU_OPTIMIZED_CONVERGENCE_OPTIONS),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_299_luau_captured_shared_owner_dependency.lua",
        LUAU_ONLY,
    )
    .with_options(LUAU_OPTIMIZED_OPTIONS),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_300_luau_captured_shared_repeat_condition.lua",
        LUAU_ONLY,
    )
    .with_options(LUAU_OPTIMIZED_OPTIONS),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_301_numeric_for_mutated_binding_capture.lua",
        MUTABLE_NUMERIC_FOR_BINDING_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_302_luau_numeric_for_multi_read_binding.lua",
        LUAU_ONLY,
    )
    .with_options(LuaCaseOptions {
        recompile_rounds: Some(4),
        ..LUAU_OPTIMIZED_OPTIONS
    }),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_303_generic_for_live_method_receiver.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_304_luau_loop_carried_binding.lua",
        LUAU_ONLY,
    )
    .with_variants(LUAU_ALL_OPTIMIZATION_VARIANTS),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_305_temp_inline_independent_runs.lua",
        LUAU_ONLY,
    )
    .with_variants(LUAU_O0_ONLY),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_306_luajit_method_protocol.lua",
        LUAJIT_ONLY,
    )
    .with_expectation(LuaCaseExpectation::LuaJitMethodProtocol),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_307_ignore_debug_policy.lua",
        ALL_DIALECTS,
    )
    .with_options(LuaCaseOptions {
        retain_debug: true,
        ignore_debug: true,
        ..LuaCaseOptions::DEFAULT
    }),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_308_debug_names_all_dialects.lua",
        ALL_DIALECTS,
    )
    .with_options(LuaCaseOptions {
        retain_debug: true,
        ..LuaCaseOptions::DEFAULT
    })
    .with_variants(ALL_NAMING_VARIANTS),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_309_ignore_debug_keeps_validation.lua",
        PUC_LUA_51,
    )
    .with_options(LuaCaseOptions {
        retain_debug: true,
        ..LuaCaseOptions::DEFAULT
    })
    .with_expectation(LuaCaseExpectation::InvalidDebugStillRejected),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_310_open_return_captured_snapshot.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_311_repeat_exit_parallel_snapshot.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_312_cross_block_direct_snapshot.lua",
        ALL_NON_LUAU_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_313_branch_value_terminal_sink.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_314_lvalue_key_deferred_base.lua",
        ALL_DIALECTS,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_315_nested_fallback_value_merge.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_316_large_ssa_scope_identity.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_317_lua51_loop_region_ownership.lua",
        PUC_LUA_51,
    ),
    LuaCaseMatrixEntry::new(
        "tests/regress-case/regress_318_lua51_nested_break_loop_owner.lua",
        PUC_LUA_51,
    ),
];
